### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by RichardJECooke** [ericwilligers/svg-animation#46]
Hi, your svg-animation library hasn't been touched in a year and there's no readme on how to use it.

Is SMIL dead?

Please would you update the library's readme so all of us out there learning about SMIL and being directed to your polyfill can know what's going on.

Thanks,
Richard.

**Comment by ewilligers** [comment]
I will look over the open issues for this library over the next two months. I'll test with Edge; my SMIL-less fork of Chrome is not current.


The intent with this polyfill is to implement SMIL on top of the new [Web Animations API](https://www.w3.org/TR/web-animations-1/).  The hope was that we would eventually be able to polyfill SMIL with native performance (running no per-frame JavaScript), by running on top of native Web Animations.

The original polyfill of the Web Animations API support animation of both CSS properties and SVG attributes. It also included support for motion path and for 'paced' animation. This SMIL libary was built on top of that polyfill, with minor bug fixes.

Since that time, Chrome and Firefox have shipped native support for Web Animations, but only for CSS properties, not SVG attributes. Also, support for pacing hasn't shipped. Motion path has moved out of Web Animations, replaced by CSS [Motion Path](https://drafts.fxtf.org/motion-1/). 

CSS Motion Path has shipped natively in Chrome, and a cross-browser [polyfill](https://github.com/Motion-Path-Polyfill/motion-path-js) is now in development. Most of my time has recently been taken up by Motion Path.

Many SVG attributes are now available as presentation attributes (CSS properties).

Thus there currently exists a path to native performance for much of SMIL, but not all of it. If and when there are browsers with native Web Animations support but no SMIL support, this would be worth exploring.
